# Yuliia Chernysheva 
## Date: February 20, 2026 

### **Instructions** 

* What is the average value of the second column?
* What is the average value of the first 5 rows of the third and fourth columns?
* Create a 10 x 10 array from random_integers array named arrayTenByTen
* Create a new array from the arrayTenByTen that is one rank and called arrayTenFlat
* What is the sum of arrayTenFlat?
* Iterate through arrayTenFlat
* What is the value of the element (9,2) in random_integers array?
* What is the data type of arrayTenFlat?
* In arrayTenFlat replace the value in index 5 with 42
* Save the array random_integers to a file.  List the directory showing the saved array.


In [25]:
import numpy as np

# Optional: make arrays print a bit nicer for class demos
np.set_printoptions(precision=3, suppress=True)

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


In [26]:
np.random.seed(21)
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [27]:
# 1. What is the average value of the second column?
mean_cols = random_integers.mean(axis=0)
print("The average value of the second column:\n", mean_cols[1])

# 2. What is the average value of the first 5 rows of the third and fourth columns?
data_slice = random_integers[:5,2:4]
print("\nThe average value of the first 5 rows of the third and fourth columns:\n", data_slice.mean())

# 3. Create a 10 x 10 array from random_integers array named arrayTenByTen
arrayTenByTen = random_integers.reshape(10, 10).copy()
print("\n10 x 10 array from random_integers array:\n", arrayTenByTen)

The average value of the second column:
 214895.8

The average value of the first 5 rows of the third and fourth columns:
 286058.5

10 x 10 array from random_integers array:
 [[ 80842 333008 202553 140037  81969  63857  42105 261540 481981 176739]
 [489984 326386 110795 394863  25024  38317  49982 408830 485118  16119]
 [407675 231729 265455 109413 103399 174677 343356 301717 224120 401101]
 [140473 254634 112262  25063 108262 375059 406983 208947 115641 296685]
 [444899 129585 171318 313094 425041 188411 335140 141681  59641 211420]
 [287650   8973 477425 382803 465168   3975  32213 160603 275485 388234]
 [246225  56174 244097   9350 496966 225516 273338  73335 283013 212813]
 [ 38175 282399 318413 337639 379802 198049 101115 419547 260219 325793]
 [148593 425024 348570 117968 107007  52547 180346 178760 305186 262153]
 [ 11835 449971 494184 472031 353049 476442  35455 191553 384154  29917]]


In [28]:
# 4. Create a new array from the arrayTenByTen that is one rank and called arrayTenFlat
arrayTenFlat = arrayTenByTen.flatten()    # reshape(-1).copy()
print("A new array from the arrayTenByTen that is one rank:\n", arrayTenFlat)

# 5. What is the sum of arrayTenFlat?
print("\nThe sum of arrayTenFlat:\n", arrayTenFlat.sum())

A new array from the arrayTenByTen that is one rank:
 [ 80842 333008 202553 140037  81969  63857  42105 261540 481981 176739
 489984 326386 110795 394863  25024  38317  49982 408830 485118  16119
 407675 231729 265455 109413 103399 174677 343356 301717 224120 401101
 140473 254634 112262  25063 108262 375059 406983 208947 115641 296685
 444899 129585 171318 313094 425041 188411 335140 141681  59641 211420
 287650   8973 477425 382803 465168   3975  32213 160603 275485 388234
 246225  56174 244097   9350 496966 225516 273338  73335 283013 212813
  38175 282399 318413 337639 379802 198049 101115 419547 260219 325793
 148593 425024 348570 117968 107007  52547 180346 178760 305186 262153
  11835 449971 494184 472031 353049 476442  35455 191553 384154  29917]

The sum of arrayTenFlat:
 23526182


In [29]:
# 6. Iterate through arrayTenFlat
print("Iterate through arrayTenFlat:")
for item in np.nditer(arrayTenFlat):
    print(int(item), end=" ")

Iterate through arrayTenFlat:
80842 333008 202553 140037 81969 63857 42105 261540 481981 176739 489984 326386 110795 394863 25024 38317 49982 408830 485118 16119 407675 231729 265455 109413 103399 174677 343356 301717 224120 401101 140473 254634 112262 25063 108262 375059 406983 208947 115641 296685 444899 129585 171318 313094 425041 188411 335140 141681 59641 211420 287650 8973 477425 382803 465168 3975 32213 160603 275485 388234 246225 56174 244097 9350 496966 225516 273338 73335 283013 212813 38175 282399 318413 337639 379802 198049 101115 419547 260219 325793 148593 425024 348570 117968 107007 52547 180346 178760 305186 262153 11835 449971 494184 472031 353049 476442 35455 191553 384154 29917 

In [30]:
# 7. What is the value of the element (9,2) in random_integers array?
print("The value of the element (9,2) in random_integers array:\n", random_integers[9,2])

# 8. What is the data type of arrayTenFlat?
print("\nThe data type of arrayTenFlat:\n", arrayTenFlat.dtype)

# 9. In arrayTenFlat replace the value in index 5 with 42
arrayTenFlat[5] = 42
print("\nIn arrayTenFlat replace the value in index 5 with 42:\n", arrayTenFlat)

The value of the element (9,2) in random_integers array:
 141681

The data type of arrayTenFlat:
 int64

In arrayTenFlat replace the value in index 5 with 42:
 [ 80842 333008 202553 140037  81969     42  42105 261540 481981 176739
 489984 326386 110795 394863  25024  38317  49982 408830 485118  16119
 407675 231729 265455 109413 103399 174677 343356 301717 224120 401101
 140473 254634 112262  25063 108262 375059 406983 208947 115641 296685
 444899 129585 171318 313094 425041 188411 335140 141681  59641 211420
 287650   8973 477425 382803 465168   3975  32213 160603 275485 388234
 246225  56174 244097   9350 496966 225516 273338  73335 283013 212813
  38175 282399 318413 337639 379802 198049 101115 419547 260219 325793
 148593 425024 348570 117968 107007  52547 180346 178760 305186 262153
  11835 449971 494184 472031 353049 476442  35455 191553 384154  29917]


In [31]:
# 10. Save the array random_integers to a file.  List the directory showing the saved array.
np.save("week6_homework_array.npy", random_integers)
np.savetxt("week6_homework_array.csv", random_integers, delimiter=",", fmt="%.2f")

print("Saved: week6_homework_array.npy and week6_homework_array.csv\n")
!dir week6_homework_array*

Saved: week6_homework_array.npy and week6_homework_array.csv

week6_homework_array.csv  week6_homework_array.npy


In [32]:
print("Name: Yuliia Chernysheva | Assignment: HW#6 | Date: 2/20/2026")

Name: Yuliia Chernysheva | Assignment: HW#6 | Date: 2/20/2026
